q1:
  payload:
    {
      "Id": 0,
      "ApplyShop": "21172697",
      "ShopType": "SH",
      "ItemId": 2830916,
      "ItemName": "网球鞋",
      "PictureUrl": "",
      "BegDate": "2024/05/29 11:21:51",
      "EndDate": "2024/06/06 11:21:51",
      "ShipDate": "2024/07/31",
      "LastPaymentBegDate": "2024/07/04 11:21:51",
      "LastPaymentEndDate": "2024/07/18 11:21:51",
      "PreSaleDtlList": [ {
        "Id": 0,
        "ItemId": 2830916,
        "BarId": 12102605,
        "SalePrice": 0.01,
        "SkuAttrValsEx": "白色,L",
        "Stocks": 0,
        "PreSalePrice": 10,
        "Qty": 10,
        "PresalePay": 1,
        "PresalePayBig": 8,
        "CouponId": -1,
        "CouponName": "" } ],
      "Status": "true",
      "PresaleType": "true",
      "StockType": "true",
      "IsShowAdvance": 0,
      "LimitQty": 0,
      "IsPrimary": 0,
      "IsVipDiscount": "false",
      "IsCoupon": "false",
      "AllowChangeShop": "true",
      "ShipType": "false",
      "ShipDay": "",
      "MinSaleQty": 1,
      "IsGradeLimit": "false",
      "VipGrades": "",
      "Scene": 1,
      "BuyConditions": 0,
      "CouponId": 79527,
      "CouponName": "Hubert_邀请券_无门槛",
      "IsJustPresale": "true"
    }
tp:
  payload:
    {
      "Id": 0,
      "ApplyShop": "10000048",
      "ShopType": "SH",
      "ItemId": 12976542,
      "ItemName": "商品中心最新T00100001",
      "PictureUrl": "https://imgc1-tp.ezrpro.com/img/186/2401182f1c8ae9429ac50001002382.png",
      "BegDate": "2024/06/12 11:59:29",
      "EndDate": "2025/07/10 11:59:29",
      "ShipDate": "2027/06/04",
      "LastPaymentBegDate": "2026/09/04 11:59:29",
      "LastPaymentEndDate": "2026/09/30 11:59:29",
      "PreSaleDtlList": [ {
        "Id": 0,
        "ItemId": 12976542,
        "BarId": 19696193,
        "SalePrice": 124,
        "SkuAttrValsEx": "规格3",
        "Stocks": 0,
        "PreSalePrice": 10,
        "Qty": 10,
        "PresalePay": 1,
        "PresalePayBig": 8,
        "CouponId": 274,
        "CouponName": "dd无门槛邀请券"
      }, {
        "Id": 0,
        "ItemId": 12976542,
        "BarId": 19696192,
        "SalePrice": 123,
        "SkuAttrValsEx": "01",
        "Stocks": 0,
        "PreSalePrice": 10,
        "Qty": 10,
        "PresalePay": 1,
        "PresalePayBig": 8,
        "CouponId": 274,
        "CouponName": "dd无门槛邀请券"
      } ],
      "Status": true,
      "PresaleType": true,
      "StockType": true,
      "IsShowAdvance": 0,
      "LimitQty": 0,
      "IsPrimary": 0,
      "IsVipDiscount": false,
      "IsCoupon": false,
      "AllowChangeShop": true,
      "ShipType": false,
      "ShipDay": 0,
      "MinSaleQty": 1,
      "IsGradeLimit": false,
      "VipGrades": "",
      "Scene": 1,
      "BuyConditions": 0,
      "CouponId": 274,
      "CouponName": "dd无门槛邀请券",
      "IsJustPresale": true
    }